### ISSUE TITLE
Glutin example doesn't work on Intel hardware under Win32

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-rs#566]
It is reported to be rendered as white regardless of the clear color. We need someone with Intel on board to investigate.

**Comment by tomaka** [comment]
There are troubles with windows 8 and glutin: https://github.com/tomaka/glium/blob/master/src/context/glutin_context.rs#L68-69

I chose not to call `glFlush` in glutin to leave the choice to the user, and left a note in the README: https://github.com/tomaka/glutin#win32

**Comment by tomaka** [comment]
Note that this is not because of glium's background thread stuff. Even the basic glutin example which contains raw OpenGL calls shows a white screen on windows 8 if you don't flush.

**Comment by kvark** [comment]
@tomaka Thanks for the info!
(of course it's not about glium, it happens in gfx+glutin example)

How does glfw handle this? Does it detect Win8 and force `glFlush`?

**Comment by tomaka** [comment]
> (of course it's not about glium, it happens in gfx+glutin example)

This flush issue that I report here is just a guess. I don't know if the person who has this problem uses windows 8. On windows 7 it works without flushing.

> How does glfw handle this? Does it detect Win8 and force glFlush?

I think glfw doesn't need it because the window was created in the same thread as where swap_buffers is called.

Basically glfw tells you to do everything in the main thread, and use multithreading at your own risks. When I wrote glutin there were still green threads in the language, so to make it safe I create a background native thread on win32. I've been thinking of changing this for some time now, but haven't done anything yet.

**Comment by kvark** [comment]
@tomaka oh I see now. So Glutin has a thread on its own and that causes the issue.
Perhaps, you could do a glutin branch with more aggressive changes, while Servo keeps using the original one?

**Comment by rpjohnst** [comment]
I was the one who reported this on IRC; I am on Windows 8. Adding a glFlush call fixes it. Replaying an apitrace also does not have the problem (I imagine apitrace replays are single threaded?)

**Comment by kvark** [comment]
@rpjohnst Thanks for joining the discussion!
I don't understand one thing: if it's a Glutin issue, why Glutin+Glium worked fine?

**Comment by rpjohnst** [comment]
Glium does call glFlush each frame, here: https://github.com/tomaka/glium/blob/ec8d3541b49ed8ad81e4560f2169489954d0bb89/src/context/glutin_context.rs#L69

**Comment by kvark** [comment]
Ok, considering this issue to be resolved then. We don't have any integration with glfw/glutin at the moment (see #529 ), so the issue lies beyond our scope.
