### ISSUE TITLE
Using shader parameters with generic code

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx-rs#606]
See https://github.com/PistonDevelopers/gfx_graphics/issues/139

The problem is that one has to pass an object implementing `Resources` to the `#[shader_param(R)]`. In the cube example, this is done by `use gfx_device_gl::GlResources as R;`.

To use it with generic code, the parameter would have to be generic or allowed to be concrete (not depending on `Resources`).

**Comment by bjz** [comment]
Agreed. I wonder if we could have something like:

~~~rust
#[shader_param]
struct TestParam<R: Resources> {
    a: i32,
    b: [f32; 4],
    c: gfx::shade::TextureParam<R>,
    d: gfx::RawBufferHandle<R>,
    e: f32,
    #[name = "a_f"]
    f: [f32; 4],
}
~~~

**Comment by kvark** [comment]
@bvssvni to be clear, you only need to pass `GlResources` for the `shader_param` definition. Everything that works with with it is still abstract, since `ShaderParam::Resources` is a usable and matchable associated type.

@bjz It would certainly be better, and I tried that. Since we are using `generic::TraitDef`, it automatically inserts its own bounds on any generic parameters that we try to have in the structure. I don't know how to override it.

**Comment by kvark** [comment]
@eddyb :
> don't use deriving support code for non-deriving

Created #607 for that. Hopefully, we'll patch it soon.

**Comment by kvark** [comment]
Ok, I've done this. @bjz please see #609
