### ISSUE TITLE
Window abstraction

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-rs#678]
We need this, because:
  - `swap_buffers()`  can be conveniently paired with `device.after_frame()` and `factory.cleanup()`. It can be done by `Graphics`, which needs to know about the window (see #666)
  - basis for the main frame (see #681)
  - basis for glutin/glfw/sdl integration (see #529)

There is an argument over Piston compatibility, which doesn't like our `Graphics` holding a window. Further discussion may be here.

**Comment by bvssvni** [comment]
Would it be an idea to modify or extend Piston to support this?

I'm OK with any solution that doesn't require us to maintain 2 different sets of window back-ends.

**Comment by bvssvni** [comment]
We could add a `.swap_buffers(bool)` to the Piston event loop which will fix the compability issue.

Then it remains to decide what to do with the interface `Graphics` needs to know. Is it possible to add this to pistoncore-window, or does it needs Gfx-specific types?

**Comment by bvssvni** [comment]
I opened https://github.com/PistonDevelopers/event_loop/issues/79

**Comment by bvssvni** [comment]
Forcing people to use Piston in order to use Gfx isn't in my interest or anybody else.

I can see a problem of adding window abstraction to Gfx, because you need glue code.

1) It might be that some people are not interested in the Piston event loop, but maybe by modifying pistoncore-window we could reuse the sdl2_window, glutin_window and glfw_window glue code in Gfx projects. I don't know how that would look like, so to find out if that's acceptable then we'll have to do some experiments. I suspect that this won't be a satisfying solution.

2) Another alternative is to move `Graphics` out of gfx-rs and put it in a library written on top of it. This would then add the window abstraction such that people using Gfx without Piston could use it. The problem with this is that the `Graphics` object could be convenient together with Piston, and in order to do that you would have to make the glue code for Gfx work with the glue code in Piston. That might be problematic.

3) Another alternative is to make the abstraction such that you do not need glue code. I don't know how this would look like.

4) Another alternative is to move the parts of the window abstraction Gfx needs to a separate library, which the window back-ends in Piston can use. This would allow separate glue code libraries for Gfx if wanted, but might still make it very convenient to use `Graphics` with Piston.

Among these options 4 looks like most reasonable. Thoughts?

**Comment by bvssvni** [comment]
I've added the feature of disabling swapping buffers in Piston.

**Comment by kvark** [comment]
@bvssvni thanks for your input! I'll get back with more info once I'm able to experiment with this a bit to see what we really need from the abstraction.

**Comment by kvark** [comment]
I think I figured how to share more code with Piston but still support stand-alone operation, mostly:
  - gfx-rs gets a `Window` trait
  - `gfx/gfx_window_glutin` is created that integrates with Glutin
  - `PistonDevelopers/gfx_window` is created to auto-implement `gfx::Window` for anything that implements piston `Window`

Thus, in the beginning we'll just need a bit of Glutin glue. That's not much, really, comparing to Piston's window implementation, since we aren't messing with events or anything like that. Whenever we want, we can add more glues.

The only unresolved part is what to do with the `swap_buffers`. I think we can postpone this for now, there is plenty of work cut out for us already.

**Comment by bvssvni** [comment]
Looks like a good idea! We could also add some helper methods to `gfx_window` if needed.

**Comment by kvark** [comment]
Funny... I started implementing everything and then realized that if we don't need `swap_buffers` right now, there is no need to have the window abstraction at all! An actual window can just implement `gfx::Output` and we are gold ;)
