### ISSUE TITLE
Cargo dependency policy

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-rs#723]
Currently, we have all the gfx-related dependencies as Git paths. However, since we are aiming to be rust-beta compatible, maybe we should start using `crates.io` again? I'm not sure what the proper policy is... The benefit is - better discover-ability, less dependency on Git. The downside is - our headache to update all the crates when a breaking change sneaks in.

cc @csherratt @bvssvni @bjz @cmr

**Comment by bvssvni** [comment]
Using crates.io is a bit cumbersome because you don't know precisely what's there. The more crates you have the bigger problem. In Piston we work against git dependencies whenever possible, and use commented versions that tells what is on crates.io. I think the issue is how stable the library is, if it it is almost stable then this becomes a less problem.

**Comment by mitchmindtree** [comment]
I'd love it if everyone started to stay on top of crates.io publishing more - the most frustrating thing I find about git dependencies is that I can't host my own crate on crates.io.

This might sound crazy, but I'd really appreciate some sort of travis script that could automatically increment the end integer (if the version hasn't changed since the last publish) and attempt to `cargo publish` whenever new code builds successfully and is merged into master. Even if it resulted in crazy versions like 0.1.4567, at least it would be available.

**Comment by csherratt** [comment]
This is actually an important problem to solve right. Currently, `gfx` ecosystem is developing a nice little stack where you need to use all the pieces you are interested in to get anything done. The pieces themselves will grab the correct dependencies that they specify in there Cargo.toml.

The problem arises when these two are in disagreement of which gfx to use. Cargo does not actually see this as a problem and will compile both. You then get a useless error message like ```Trying to use `gfx::FooBar` expected `gfx::FooBar` ```. This happens since the `gfx` is different for the types.

Cargo.io is actually a pretty good solution to this problem if we use the `version` correctly. Since everything is bound to come from Cargo.io, you won't have to deal with something including git randomly. That being said, if one component uses a more strict `version` then another. I'm pretty sure we are in the same boat.

@mitchmindtree I don't have a problem with automation in general, but I will point out that this may causes semver abuse. Since the minor needs to be incremented when publishing adding apis.

**Comment by kvark** [comment]
Ok, after the gfx-0.5 breakage of user libraries and some stabilization of Rust, I'm leaning towards using crates.io for dependencies. We can use `version = "0.y.*"` to keep the last patched non-breaking dependency both between gfx libraries and in the user code.

**Comment by kvark** [comment]
Fixed with #759 landing
